import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Module as ModuleEntity } from '../entities/module.entity';
import { Lesson } from '../entities/lesson.entity';
import { Quiz } from '../entities/quiz.entity';
import { Question } from '../entities/question.entity';

interface LessonSeed { order: number; title: string; content: string; }
interface QuestionSeed { questionText: string; options: string[]; correctAnswer: number; explanation: string; }
interface ModuleSeed {
  order: number; title: string; description: string; isPremium: boolean; passingScore: number;
  lessons: LessonSeed[];
  quiz: { title: string; questions: QuestionSeed[] };
}

@Injectable()
export class SeedService {
  private readonly logger = new Logger(SeedService.name);
  constructor(
    @InjectRepository(ModuleEntity) private modulesRepo: Repository<ModuleEntity>,
    @InjectRepository(Lesson) private lessonsRepo: Repository<Lesson>,
    @InjectRepository(Quiz) private quizzesRepo: Repository<Quiz>,
    @InjectRepository(Question) private questionsRepo: Repository<Question>,
  ) {}

  /**
   * Detects stale (old) seed data by checking module titles.
   * Old modules had generic titles like "Anatomía del RTP".
   * New modules have API-norm-specific titles.
   * Runs reset + reseed automatically on first deploy with new code.
   */
  async autoMigrateIfStale() {
    const count = await this.modulesRepo.count();
    if (count === 0) {
      this.logger.log('DB vacía — ejecutando seed inicial...');
      return this.runSeed();
    }
    // Check if the first module has the old title (old seed)
    const firstModule = await this.modulesRepo.findOne({ where: { order: 1 } });
    const expectedTitle = 'Fundamentos del RTP — Alcance y Clasificación API 15S';
    if (firstModule && firstModule.title !== expectedTitle) {
      this.logger.log(`⚠️  Seed desactualizado detectado (título: "${firstModule.title}"). Migrando a contenido técnico API...`);
      return this.reset();
    }
    this.logger.log('✅ Seed actualizado — no se requiere migración.');
  }

  async reset() {
    this.logger.log('Resetting seed: eliminando módulos, lecciones, quizzes y preguntas...');
    // Delete in dependency order
    await this.questionsRepo.query('DELETE FROM "questions"');
    await this.quizzesRepo.query('DELETE FROM "quizzes"');
    await this.lessonsRepo.query('DELETE FROM "lessons"');
    await this.modulesRepo.query('DELETE FROM "modules"');
    this.logger.log('Reset completado. Ejecutando seed...');
    return this.runSeed();
  }

  async run() {
    const count = await this.modulesRepo.count();
    if (count > 0) {
      this.logger.log('Seed ya ejecutado. Omitiendo...');
      return { message: 'Seed ya ejecutado previamente. Usa /seed/reset para reiniciar.' };
    }
    return this.runSeed();
  }

  private async runSeed() {
    this.logger.log('Iniciando seed técnico — 9 módulos API 15S / 15SA / 15SIH / 17J...');

    const modules: ModuleSeed[] = [
      {
        order: 1, isPremium: false, passingScore: 70,
        title: 'Fundamentos del RTP — Alcance y Clasificación API 15S',
        description: 'Alcance, clasificación de servicio y requisitos generales de API Spec 15S para tubería termoplástica reforzada spoolable en petróleo y gas.',
        lessons: [
          { order: 1, title: 'Alcance, jerarquía normativa y límites de aplicación de API 15S',
            content: '## Por qué existe API 15S\n\nAntes de la primera edición de API 15S (2006), los fabricantes de RTP publicaban especificaciones propietarias incomparables entre sí. Un operador no podía verificar si los datos del fabricante A y el fabricante B eran equivalentes. API 15S resolvió eso: es un **protocolo de calificación** común que cualquier fabricante debe demostrar cumplir.\n\nEsto tiene consecuencias prácticas importantes:\n- El certificado API 15S **no lo emite API** — lo emite el fabricante a partir de sus propios ensayos\n- El operador es responsable de verificar que los ensayos de tipo estén vigentes y cubran las condiciones del proyecto\n- Un producto sin Type Test Report actualizado no puede considerarse calificado, aunque tenga logo API\n\n---\n\n## 📐 Parámetros de cobertura de la norma\n\n| Parámetro | Rango cubierto | Límite crítico |\n|---|---|---|\n| Presión de trabajo (NWP) | Hasta **3,500 psi** (241 bar) | A **23 °C** de referencia |\n| Diámetro nominal | **½\" a 4\"** (DN 15 a DN 100) | Fuera de rango → no aplica |\n| Temperatura de referencia | **23 °C** | TDF requerido para T > 23 °C |\n| Fluido de diseño | Hidrocarburos líquidos, agua, gas | Ver clase de servicio A/B |\n\n---\n\n## Qué define — y qué no define — la norma\n\nAPI 15S define los **requisitos de producto** que el fabricante debe demostrar:\n\n- Materiales calificados: liner, refuerzo y jacket con propiedades mínimas verificadas\n- Proceso de fabricación: parámetros controlados que deben quedar en el registro de producción\n- Ensayos de tipo: protocolo mínimo para demostrar desempeño a largo plazo\n- Documentación: qué debe declarar el PDS, qué debe contener el Mill Certificate\n\n**API 15S NO cubre:**\n- Diseño de la red (dimensionamiento hidráulico, análisis de esfuerzos del sistema)\n- Manejo, transporte e instalación en campo → eso es API RP 15SIH\n- Inspección y gestión de integridad en operación → eso es API RP 15SA\n\n> **Clave para el ingeniero:** cuando un proveedor dice que su producto "cumple API 15S", debes solicitar el Type Test Report y verificar que los ensayos cubren la presión, temperatura y clase de servicio específicas de tu proyecto. Si el ensayo se hizo a 23 °C y tu operación es a 60 °C sin TDF documentado, el producto NO está calificado para tu aplicación.' },
          { order: 2, title: 'Clasificación de servicio y factor de temperatura TDF',
            content: '## Clase A vs. Clase B: qué significa en la práctica\n\nLa clasificación no es solo una etiqueta. Determina el protocolo de ensayo de calificación y los materiales admisibles del fitting:\n\n| Clase | Fluido | Implicación en ensayos |\n|---|---|---|\n| **Clase A** | Sin H₂S libre, sin CO₂ agresivo, sin salmueras de alta salinidad | Ensayos estándar de presión y temperatura en agua |\n| **Clase B** | H₂S < 1 mol%, CO₂ libre, o salmueras > 35,000 ppm TDS | Ensayos adicionales: inmersión química, permeación, resistencia de liner en fluido representativo |\n\nUsar un producto Clase A en un fluido con H₂S es un error de ingeniería que puede resultar en falla del liner por degradación química sin señales externas visibles.\n\n---\n\n## El TDF: cómo funciona la desclasificación por temperatura\n\nEl polietileno pierde resistencia mecánica al aumentar la temperatura. Esta pérdida es cuantificada por el **Temperature Derating Factor (TDF)**:\n\n`NWP_efectiva (T) = NWP_23°C × TDF(T)`\n\nEjemplo real de tabla TDF para un RTP con liner HDPE PE-100:\n\n| Temperatura | TDF | NWP efectiva (si NWP base = 200 bar) |\n|---|---|---|\n| 23 °C | 1.00 | 200 bar |\n| 40 °C | 0.84 | 168 bar |\n| 60 °C | 0.63 | 126 bar |\n| 80 °C | 0.45 | 90 bar |\n\nEl TDF no es un valor genérico de la norma — cada fabricante lo determina mediante ensayo LTHS a múltiples temperaturas según ISO/TR 9080. Si el PDS del fabricante no incluye tabla TDF, no puedes operar sobre 23 °C.\n\n---\n\n## Regla de calificación independiente\n\nCada combinación de variables requiere calificación propia:\n\n- **Diámetro:** ½\", ¾\", 1\", 1½\", 2\", 3\", 4\" → calificación por diámetro\n- **Presión:** cada nivel de NWP ensayado\n- **Temperatura:** por encima de la TDF validada, el producto no está calificado\n- **Clase de servicio:** A ≠ B\n\n> Un ingeniero que especifica un RTP de 2\" Clase A calificado a 150 bar/23°C para una línea de 180 bar/50°C con trazas de CO₂ está usando el producto fuera de su envolvente de calificación — sin importar que "sea del mismo fabricante". Ambas condiciones están fuera del rango calificado.' },
          { order: 3, title: 'Arquitectura de capas: materiales, funciones y criterios de selección',
            content: '## Capa 1 — Liner interior: la barrera de proceso\n\nEl liner es el único componente en contacto directo con el fluido. Su integridad define la hermeticidad del sistema.\n\n**Materiales y su clasificación ASTM D3350:**\n\n| Material | Código MRS | T máx. típica | Característica |\n|---|---|---|---|\n| HDPE PE-80 | MRS 8.0 MPa | 60 °C | Menor costo, aplicaciones estándar |\n| HDPE PE-100 | MRS 10.0 MPa | 60 °C | Mayor resistencia, liner más delgado |\n| XLPE (reticulado) | — | 90 °C | Alta temperatura, sin fusión |\n\nEl criterio de selección no es solo temperatura: la resistencia química al fluido específico debe verificarse. El HDPE es resistente a hidrocarburos alifáticos pero puede hincharse con algunos aromáticos (benceno, tolueno) a alta concentración.\n\n---\n\n## Capa 2 — Refuerzo estructural: la capacidad de presión\n\nEl refuerzo helicoidal convierte presión interna en tensión circunferencial absorbida por las fibras. El **ángulo de enrollado** determina el balance entre capacidad de presión y carga axial:\n\n- Ángulo ~54.7° (ángulo neutro): equilibrio óptimo presión/tensión axial\n- Ángulo alto (>60°): mayor resistencia a presión, menor a tensión axial\n- Ángulo bajo (<50°): mayor resistencia axial, menor a presión\n\n**Materiales de refuerzo:**\n\n| Material | Resistencia a tracción | SSC con H₂S | Costo relativo |\n|---|---|---|---|\n| Fibra de aramida (Kevlar®/Twaron®) | ~3,600 MPa | No susceptible | Alto |\n| Fibra de vidrio E | ~1,700 MPa | No susceptible | Bajo |\n| Fibra de vidrio S | ~2,700 MPa | No susceptible | Medio |\n| Alambre de acero trefilado | ~1,900 MPa | **Susceptible** | Bajo |\n\nPara fluidos con H₂S (sour service), el alambre de acero queda descartado porque el H₂S que permea el liner se acumula en el anular y puede causar Sulfide Stress Cracking (SSC) en el refuerzo metálico.\n\n---\n\n## Capa 3 — Jacket exterior: la primera línea de defensa\n\nEl jacket no aporta resistencia a la presión, pero protege el refuerzo del daño mecánico que sería la principal causa de falla en campo. Requisitos mínimos API 15S:\n\n- Material: HDPE o MDPE\n- **Carbon Black ≥ 2% en peso**: necesario para absorber radiación UV y prevenir degradación fotoquímica. Sin él, el jacket se vuelve frágil en 6-18 meses de exposición solar.\n- Espesor mínimo: declarado en PDS, verificado en el Mill Certificate\n\n---\n\n## Regla de re-calificación: cuándo aplica\n\nCualquier cambio que afecte las propiedades calificadas exige repetir los ensayos de tipo:\n\n- Cambio de proveedor de fibra de refuerzo (mismo tipo, distinto fabricante)\n- Cambio en formulación del compuesto de HDPE del liner\n- Cambio en ángulo de enrollado o número de capas\n- Cambio en parámetros de proceso (temperatura de extrusión, velocidad de línea)\n\nEsto es crítico: un fabricante que "mejora" su proceso sin re-calificar puede estar suministrando un producto sin respaldo de ensayo actual.' },
        ],
        quiz: {
          title: 'Evaluación M1 — API 15S: Alcance, Clasificación y Arquitectura',
          questions: [
            { questionText: '¿Quién emite formalmente el certificado de conformidad con API 15S?', options: ['El organismo API directamente', 'Un laboratorio acreditado independiente', 'El propio fabricante, con base en sus ensayos de tipo', 'El operador del sistema instalado'], correctAnswer: 2, explanation: 'API 15S es una especificación de auto-declaración: el fabricante realiza los ensayos de tipo y emite el certificado. API no certifica productos individuales.' },
            { questionText: 'Un fabricante cambia el proveedor de fibra de aramida manteniendo el mismo ángulo de enrollado. ¿Qué debe hacer según API 15S?', options: ['Notificar a API por escrito', 'Re-calificar el producto con nuevos ensayos de tipo completos', 'Actualizar solo el PDS con el nuevo proveedor', 'Nada si el ángulo de enrollado no cambió'], correctAnswer: 1, explanation: 'Cualquier cambio en materiales — incluido el proveedor de fibra — requiere re-calificación de tipo completa. Las propiedades de la fibra dependen del fabricante.' },
            { questionText: 'Un RTP tiene NWP = 160 bar a 23 °C y TDF = 0.63 a 60 °C. ¿Cuál es la presión de trabajo admisible a 60 °C?', options: ['160 bar', '101 bar', '63 bar', '253 bar'], correctAnswer: 1, explanation: 'NWP_efectiva = NWP × TDF = 160 × 0.63 = 100.8 bar ≈ 101 bar. El TDF reduce proporcionalmente la presión nominal.' },
            { questionText: '¿Por qué el refuerzo de alambre de acero no se recomienda para fluidos con H₂S (sour service)?', options: ['El acero reacciona con el HDPE del liner', 'El H₂S que permea el liner se acumula en el anular y puede causar SSC en el alambre', 'El acero trefilado no soporta las presiones de sour service', 'La norma API 15S prohíbe explícitamente el acero en sour service'], correctAnswer: 1, explanation: 'El H₂S es una molécula pequeña que puede difundir a través del liner HDPE y acumularse en el anular. En el anular, puede causar Sulfide Stress Cracking (SSC) en el refuerzo de acero.' },
            { questionText: '¿Qué norma clasifica el polietileno del liner según su Minimum Required Strength (MRS)?', options: ['API 15S directamente', 'ASTM D3350', 'ISO 4427', 'ASME B31.3'], correctAnswer: 1, explanation: 'ASTM D3350 es la norma de clasificación del polietileno para tuberías y accesorios. Define el MRS que distingue PE-80 (MRS 8.0 MPa) de PE-100 (MRS 10.0 MPa).' },
            { questionText: '¿Cuál es el ángulo de enrollado del refuerzo que produce el mejor equilibrio entre resistencia a presión y carga axial?', options: ['30°', '45°', '54.7° (ángulo neutro)', '80°'], correctAnswer: 2, explanation: 'A ~54.7° (arctan √2), la relación entre esfuerzo circunferencial y axial es exactamente 2:1, coincidiendo con la relación de presión interna para cilindro de pared delgada. Es el ángulo neutro óptimo.' },
            { questionText: 'Un operador detecta que su contrato especifica un RTP Clase A para una línea con 0.5 mol% de H₂S. ¿Cuál es el problema técnico?', options: ['La presión puede ser demasiado alta para Clase A', 'Clase A no tiene ensayos de resistencia química para H₂S; el liner puede degradarse sin señal externa', 'No hay problema: 0.5 mol% está bajo el umbral', 'Solo es problema si la temperatura supera 40 °C'], correctAnswer: 1, explanation: 'Clase A no incluye ensayos de permeación ni inmersión química en fluidos con H₂S. La degradación del liner puede ocurrir silenciosamente. La aplicación requiere Clase B como mínimo.' },
            { questionText: '¿Qué diferencia práctica hay entre un liner de PE-100 y uno de PE-80 en un RTP?', options: ['PE-100 opera a mayor temperatura máxima', 'PE-100 tiene mayor MRS, permitiendo un liner más delgado a igual presión', 'PE-80 resiste mejor el H₂S', 'No hay diferencia en aplicaciones de campo'], correctAnswer: 1, explanation: 'El MRS más alto del PE-100 (10.0 vs 8.0 MPa) permite reducir el espesor del liner manteniendo la misma resistencia, lo que reduce peso y mejora la flexibilidad del RTP.' },
            { questionText: 'Un fabricante no incluye tabla TDF en el PDS de su producto RTP. ¿Qué implica para el operador?', options: ['Puede operar hasta 40 °C sin restricción', 'El producto no puede usarse en ninguna temperatura sobre 23 °C de forma justificada', 'Debe solicitar el TDF al distribuidor', 'El TDF estándar de 0.8 aplica automáticamente'], correctAnswer: 1, explanation: 'Sin tabla TDF publicada en el PDS, no existe base técnica para operar sobre 23 °C. No existe TDF "por defecto" — debe ser determinado por ensayo específico del fabricante.' },
            { questionText: '¿Por qué el jacket exterior debe tener ≥ 2% de Carbon Black en peso?', options: ['Para aumentar la conductividad eléctrica del sistema', 'Para prevenir la degradación fotoquímica del HDPE por radiación UV', 'Para reducir la permeación de gases al anular', 'Para facilitar la detección óptica del tubo en campo'], correctAnswer: 1, explanation: 'El Carbon Black actúa como absorbente UV que protege las cadenas poliméricas del HDPE de la fotodegradación. Sin él, el jacket puede volverse frágil en meses de exposición solar directa.' },
          ],
        },
      },
      {
        order: 2, isPremium: false, passingScore: 70,
        title: 'Diseño y Calificación de Producto — API 15S',
        description: 'Metodología de diseño, factores de diseño, ensayos de tipo requeridos y criterios de calificación del fabricante según API Spec 15S.',
        lessons: [
          { order: 1, title: 'Presión nominal y factores de diseño',
            content: '## ⚖️ Presiones de diseño — API 15S\n\n| Parámetro | Símbolo | Definición |\n|---|---|---|\n| Presión nominal | **NWP** | Presión máx. de servicio a 23 °C |\n| Presión de ráfaga mínima | **MBP** | ≥ **4 × NWP** |\n| Factor de diseño | **FD** | 0.25 (= NWP/MBP) |\n| Prueba hidrostática de campo | **FHTP** | **1.25 × NWP** |\n\n---\n\n## 🌡️ Desclasificación por temperatura (TDF)\n\nCuando la temperatura supera **23 °C**, la presión de trabajo se reduce:\n\n- TDF se obtiene de ensayo propio del fabricante\n- Ejemplo: T = **60 °C** → TDF = **0.63** → `Presión@60°C = NWP × 0.63`\n- La tabla TDF es parte obligatoria del **Product Data Sheet (PDS)**\n\n> ⚠️ Sin tabla TDF documentada, el producto **no puede operar** por encima de 23 °C.' },
          { order: 2, title: 'Ensayos de tipo (Type Testing) requeridos por API 15S',
            content: '## 🧪 Los 6 ensayos de tipo requeridos\n\n| # | Ensayo | Condición | Criterio |\n|---|---|---|---|\n| 1 | **Presión a corto plazo** | 5 muestras a 23 °C | MBP ≥ **4 × NWP**; ninguna falla prematura |\n| 2 | **LTHS** (ISO/TR 9080) | 20 °C y 60 °C | Regresión estadística → HDB a 20 años |\n| 3 | **Flexión a temperatura** | -20 °C y +60 °C al MBR | Sin fractura ni deslaminación |\n| 4 | **Tensión axial** | Tracción hasta falla | Determina **MTAL** del sistema fitting-tubería |\n| 5 | **Presión cíclica** | **100,000 ciclos** 0 ↔ NWP | Sin fuga en ningún ciclo |\n| 6 | **Colapso** | Presión externa de diseño | Sin colapso (si aplica al servicio) |\n\n---\n\n## 📌 Reglas clave\n\n- Todos los ensayos se realizan con el **sistema completo** (tubo + fittings del fabricante)\n- Cambio de material o parámetro de proceso → **re-calificación total** requerida\n- Los resultados quedan en el **Type Test Report** del fabricante — documento clave de la oferta técnica' },
          { order: 3, title: 'Documentación de calificación y marcado del producto',
            content: '## 📄 Product Data Sheet (PDS)\n\nDocumento técnico clave del fabricante. Debe declarar:\n\n- ✅ **NWP** a 23 °C\n- ✅ **MBR** (radio mínimo de curvatura)\n- ✅ **MTAL** (carga axial máxima del sistema)\n- ✅ Rango de **temperatura** de operación\n- ✅ **Clase de servicio** calificada (A o B)\n- ✅ Tabla **TDF** por temperatura\n- ✅ Dimensiones: DN, ID, OD, masa/m\n\n---\n\n## 🏷️ Marcado permanente del tubo\n\n| Campo | Descripción |\n|---|---|\n| Fabricante | Nombre o marca registrada |\n| Lote / serie | Número de producción trazable |\n| DN | Diámetro nominal |\n| NWP | A 23 °C, en psi o bar |\n| Año | Año de fabricación |\n| Conformidad | Referencia a **API 15S** |\n\n---\n\n## 📋 Mill Certificate (Certificado de Lote)\n\nEmitido por lote de producción. Incluye:\n\n- Resultado de prueba hidrostática de producción\n- Mediciones dimensionales (OD, espesor de liner y jacket)\n- Trazabilidad de materiales (proveedor de fibra y resina)' },
        ],
        quiz: {
          title: 'Evaluación M2 — Diseño y Calificación API 15S',
          questions: [
            { questionText: '¿Cuál es el factor de diseño (MBP/NWP) mínimo de API 15S?', options: ['2.0', '2.5', '4.0', '6.0'], correctAnswer: 2, explanation: 'API 15S requiere MBP ≥ 4 × NWP, lo que equivale a un factor de diseño de 0.25.' },
            { questionText: '¿A qué temperatura de referencia se define la NWP según API 15S?', options: ['0 °C', '23 °C', '40 °C', '60 °C'], correctAnswer: 1, explanation: 'La NWP se define a la temperatura de referencia de 23 °C.' },
            { questionText: '¿Qué metodología usa API 15S para proyección de vida útil a largo plazo?', options: ['ASME VIII Div.1', 'ISO/TR 9080 (regresión estadística LTHS)', 'NACE TM0177', 'ASTM E8'], correctAnswer: 1, explanation: 'ISO/TR 9080 define el método de regresión estadística para determinar el HDB a largo plazo.' },
            { questionText: 'Si NWP = 100 bar a 23 °C y TDF a 60 °C = 0.63, ¿cuál es la presión de trabajo a 60 °C?', options: ['37 bar', '63 bar', '100 bar', '159 bar'], correctAnswer: 1, explanation: 'Presión a 60 °C = NWP × TDF = 100 × 0.63 = 63 bar.' },
            { questionText: '¿Cuántos ciclos requiere el ensayo de presión cíclica de API 15S?', options: ['10,000', '50,000', '100,000', '1,000,000'], correctAnswer: 2, explanation: 'El ensayo de presión cíclica requiere 100,000 ciclos entre 0 y NWP sin fuga ni falla.' },
            { questionText: '¿Qué ensayo determina la carga axial máxima del sistema fitting-tubería?', options: ['Ensayo LTHS', 'Ensayo de colapso', 'Ensayo de tensión axial (MTAL)', 'Ensayo de presión cíclica'], correctAnswer: 2, explanation: 'El ensayo de tensión axial determina la Maximum Tensile Axial Load (MTAL) del sistema fitting-tubería.' },
            { questionText: '¿A qué temperaturas se realiza el ensayo de flexión de API 15S?', options: ['Solo a 23 °C', 'A 0 °C y 40 °C', 'A -20 °C y +60 °C', 'A -40 °C y +80 °C'], correctAnswer: 2, explanation: 'El ensayo de flexión se realiza a -20 °C (mínima operacional) y +60 °C (máxima típica), al MBR del fabricante.' },
            { questionText: '¿Qué significa MBR en la ficha técnica de un RTP?', options: ['Maximum Burst Rating', 'Minimum Bend Radius (radio mínimo de curvatura)', 'Maximum Bore Ratio', 'Minimum Breaking Resistance'], correctAnswer: 1, explanation: 'MBR = Minimum Bend Radius, el radio mínimo al que puede curvarse el RTP sin daño estructural.' },
            { questionText: '¿Cuál es la FHTP para sistemas nuevos instalados según las recomendaciones de API 15S?', options: ['1.0 × NWP', '1.25 × NWP', '1.5 × NWP', '2.0 × NWP'], correctAnswer: 1, explanation: 'FHTP = 1.25 × NWP para sistemas nuevos instalados según práctica recomendada.' },
            { questionText: '¿Qué declara el Product Data Sheet (PDS) de un RTP API 15S?', options: ['Solo el precio y el plazo de entrega', 'NWP, MBR, MTAL, rango de temperatura, clase de servicio y tablas TDF', 'Solo el diámetro y la longitud del carrete', 'Solo los resultados del Mill Certificate'], correctAnswer: 1, explanation: 'El PDS es el documento técnico del fabricante que declara todos los parámetros de desempeño calificados del producto.' },
          ],
        },
      },
      {
        order: 3, isPremium: false, passingScore: 70,
        title: 'Fittings y Sistemas de Unión para RTP — API 15S',
        description: 'Tipos de conectores calificados, requisitos de diseño de fittings, procedimientos de instalación y control de calidad de uniones en sistemas RTP.',
        lessons: [
          { order: 1, title: 'Clasificación y tipos de fittings calificados',
            content: '## 🔩 Tipos de fittings calificados — API 15S\n\n| Tipo | Principio | Uso típico |\n|---|---|---|\n| **Compresión mecánica** | Grip sobre OD + stiffener interno | El más común en campo; sin equipo especial |\n| **Termosoldado** (electrofusión) | Resistencia eléctrica embebida | Solo liner PE; requiere equipo homologado |\n| **Roscado** NPT/BSPT | Rosca estándar | Conexión a válvulas y manifolds |\n| **Bridado** ASME B16.5 | Adaptador de brida calificado | Conexión a equipos de acero |\n\n---\n\n## ⚠️ Regla fundamental\n\n> Todos los fittings deben calificarse como **sistema completo** junto con la tubería del fabricante.\n> No es válido combinar fitting de una marca con tubo de otra sin calificación conjunta.\n\n---\n\n## 📌 ¿Cuándo usar cada tipo?\n\n- 🏗️ Campo sin electricidad → **Compresión mecánica**\n- 🔌 Taller controlado → **Electrofusión** (mayor integridad)\n- 🔧 Conexión a piping de acero → **Bridado** o **Roscado**' },
          { order: 2, title: 'Calificación del sistema fitting-tubería',
            content: '## 🧪 Ensayos de calificación del sistema\n\n| Ensayo | Condición | Duración | Criterio |\n|---|---|---|---|\n| Presión a corto plazo | **1.5 × NWP** | 1 hora | Sin fuga |\n| Carga axial (MTAL) | Hasta falla | — | Sin separación |\n| Presión a largo plazo | **1.0 × NWP** | **1,000 horas** | Sin fuga |\n\n---\n\n## 📄 Fitting Installation Procedure (FIP)\n\nEl fabricante emite el **FIP** — es parte del certificado de calificación. Especifica:\n\n- ✅ Torques de apriete por diámetro\n- ✅ Longitudes de inserción requeridas\n- ✅ Herramientas calificadas (marca y modelo)\n- ✅ Preparación de la superficie del tubo\n- ✅ Condiciones ambientales mínimas\n\n> 🔑 Seguir el FIP **al pie de la letra** es obligatorio. Cualquier desviación anula la garantía y la calificación.' },
          { order: 3, title: 'Procedimiento de instalación de fitting de compresión en campo',
            content: '## 🛠️ Instalación de fitting de compresión — Paso a paso\n\n### 1️⃣ Corte\n- Herramienta: sierra de cinta o sierra circular con guía\n- ❌ **NUNCA** amoladora angular — genera calor y corte irregular\n- Tolerancia: perpendicular al eje ±**1°** máximo\n\n### 2️⃣ Preparación\n- Limpiar con paño limpio y **alcohol isopropílico**\n- Eliminar todas las rebabas del extremo cortado\n\n### 3️⃣ Inserción del stiffener\n- Insertar hasta el **tope marcado**\n- Verificar que el tubo llega al hombro del fitting\n\n### 4️⃣ Compresión\n- Usar herramienta **hidráulica calificada** del fabricante\n- Aplicar presión y golpes según la **tabla FIP** por diámetro\n\n### 5️⃣ Registro en dossier de calidad\n\n| Campo obligatorio | Descripción |\n|---|---|\n| N° de fitting | ID correlativo de campo |\n| Operador | Nombre + certificación vigente |\n| Fecha y hora | Registro exacto |\n| Resultado | ✅ Conforme / ❌ No conforme |' },
        ],
        quiz: {
          title: 'Evaluación M3 — Fittings y Conexiones RTP',
          questions: [
            { questionText: '¿Qué función cumple el stiffener en un fitting de compresión para RTP?', options: ['Aumentar la presión de compresión', 'Soportar el diámetro interior del liner durante la compresión', 'Conectar eléctricamente el refuerzo', 'Facilitar el desmontaje'], correctAnswer: 1, explanation: 'El stiffener (insert interno) soporta el liner para evitar que colapse bajo la fuerza de compresión del fitting.' },
            { questionText: '¿Cuál es el criterio de ensayo de presión a corto plazo del sistema fitting-tubería API 15S?', options: ['1.0 × NWP, 30 min', '1.25 × NWP, 2 horas', '1.5 × NWP, 1 hora sin fuga', '2.0 × NWP, 15 min'], correctAnswer: 2, explanation: 'La calificación requiere 1.5 × NWP durante 1 hora sin fuga con el fitting instalado según FIP del fabricante.' },
            { questionText: '¿Qué herramienta está PROHIBIDA para el corte del RTP?', options: ['Sierra de cinta', 'Sierra circular con guía', 'Amoladora angular', 'Sierra reciprocante'], correctAnswer: 2, explanation: 'La amoladora genera calor que daña el liner y produce corte irregular; está prohibida por los FIPs de fabricantes.' },
            { questionText: '¿Cuánto tiempo dura el ensayo de presión a largo plazo del sistema fitting-tubería?', options: ['100 horas', '500 horas', '1000 horas', '8760 horas'], correctAnswer: 2, explanation: 'El ensayo a largo plazo requiere hermeticidad a 1.0 × NWP durante 1000 horas sin fuga.' },
            { questionText: '¿Qué norma aplica a las bridas de acero usadas con fittings bridados de RTP?', options: ['ISO 4633', 'ASME B16.5', 'API 6A', 'DIN 2501'], correctAnswer: 1, explanation: 'Los fittings bridados de RTP se conectan a bridas según ASME B16.5, norma estándar para bridas de tuberías en la industria.' },
            { questionText: '¿Qué desviación máxima se permite en el corte del extremo del RTP?', options: ['±0.5°', '±1°', '±5°', '±10°'], correctAnswer: 1, explanation: 'El corte debe ser perpendicular al eje con desviación máxima de ±1° para garantizar el asiento correcto del fitting.' },
            { questionText: '¿Qué ensayo verifica la integridad del fitting bajo fuerzas de tracción?', options: ['Ensayo LTHS', 'Ensayo de carga axial (MTAL)', 'Ensayo de presión cíclica', 'Ensayo de colapso'], correctAnswer: 1, explanation: 'El ensayo MTAL verifica que el conjunto fitting-tubería no se separe bajo la máxima carga axial de diseño.' },
            { questionText: '¿Qué tipo de fitting requiere equipo homologado y control estricto de limpieza?', options: ['Fitting de compresión mecánica', 'Fitting termosoldado (electrofusión)', 'Fitting roscado NPT', 'Fitting bridado ASME B16.5'], correctAnswer: 1, explanation: 'El fitting de electrofusión requiere equipo homologado y condiciones de temperatura y limpieza controladas.' },
            { questionText: '¿Qué información mínima debe registrarse por cada fitting en el dossier de calidad?', options: ['Solo el número de serie', 'Número de fitting, operador, fecha, hora y resultado de inspección', 'Solo el torque aplicado', 'Solo la presión de prueba'], correctAnswer: 1, explanation: 'El dossier debe incluir: número de fitting, operador certificado, fecha, hora y resultado de inspección visual.' },
            { questionText: '¿Qué documento del fabricante rige el procedimiento de instalación del fitting de compresión?', options: ['Product Data Sheet (PDS)', 'Mill Certificate', 'Fitting Installation Procedure (FIP)', 'Safety Data Sheet (SDS)'], correctAnswer: 2, explanation: 'El FIP (Fitting Installation Procedure) es el documento normativo del fabricante que especifica cada paso, torque y herramienta.' },
          ],
        },
      },
      {
        order: 4, isPremium: false, passingScore: 70,
        title: 'Instalación en Campo y Prueba Hidrostática — API RP 15S',
        description: 'Procedimientos de manejo, zanjeo, tendido y prueba hidrostática de sistemas RTP instalados según API RP 15S.',
        lessons: [
          { order: 1, title: 'Manejo, transporte y almacenamiento de carretes RTP',
            content: '## 📦 Reglas de manejo — API RP 15SIH Sección 5\n\n> ⚠️ El daño por manejo incorrecto es la principal causa de falla **antes** de la instalación.\n\n---\n\n### 🚛 Transporte\n- Posición: **horizontal** sobre superficie plana\n- Amarre: cintas textiles — ❌ NUNCA cables metálicos\n- Radio del carrete de transporte ≥ **MBR** del producto\n\n### 🏗️ Izaje\n- Usar **eslingas textiles de 4 puntos**\n- ❌ NUNCA una sola eslinga central — genera flexión concentrada\n\n### 🏭 Almacenamiento\n\n| Condición | Requisito |\n|---|---|\n| Superficie | Nivelada, sin piedras ni contaminantes |\n| Temperatura máxima | **50 °C** |\n| Exposición > 30 días | Cubrir con manta **opaca** |\n| Apilado máximo | 2 carretes sin soporte estructural |' },
          { order: 2, title: 'Zanjeo, tendido y curvado en campo',
            content: '## 🪣 Especificaciones de zanja — API RP 15SIH\n\n| Parámetro | Valor |\n|---|---|\n| Ancho mínimo | DN + 300 mm (recomendado DN + 400 mm) |\n| Cama de arena | **100 mm** mínimo, arena limpia < 3 mm |\n| Temperatura de tendido | **> 5 °C** (bajo esa T el PE se agrieta) |\n\n---\n\n## 📏 Profundidad mínima de cobertura\n\n| Zona | Cobertura mínima |\n|---|---|\n| Tierra agrícola / peatonal | **600 mm** |\n| Cruce de camino no pavimentado | **900 mm** |\n| Carretera pavimentada / vía férrea | **1,200 mm** |\n\n---\n\n## ↩️ Curvado en frío\n\n- Nunca curvar por debajo del **MBR** del fabricante\n- Para curvas más cerradas → usar **codos fabricados** certificados\n- ❌ NUNCA aplicar calor local para forzar una curva' },
          { order: 3, title: 'Procedimiento de prueba hidrostática de campo',
            content: '## 💧 Protocolo de prueba hidrostática\n\n**Presión de prueba:** `Pt = 1.25 × NWP`\n\n---\n\n## 📋 Pasos del procedimiento\n\n| Paso | Acción | Tiempo |\n|---|---|---|\n| 1️⃣ | Llenar con agua limpia + purgar **todo el aire** en venteos altos | Hasta purga completa |\n| 2️⃣ | Presurizar al **50% de Pt** | Mantener **30 min** |\n| 3️⃣ | Presurizar al **100% de Pt** | — |\n| 4️⃣ | Estabilización térmica | Mínimo **60 min** |\n| 5️⃣ | Registro oficial cada 15 min | Mínimo **4 horas** |\n| 6️⃣ | Despresurización **lenta y controlada** | — |\n\n---\n\n## ✅ Criterio de aceptación\n\n- Variación de presión (corregida por temperatura) ≤ **1%** de Pt en la última hora\n- Sin fugas visibles en ningún punto\n\n> ⚠️ Despresurizar bruscamente puede generar **vacío interno** que colapsa el liner de HDPE.' },
        ],
        quiz: {
          title: 'Evaluación M4 — Instalación y Prueba Hidrostática',
          questions: [
            { questionText: '¿Cuál es la temperatura mínima recomendada para tender RTP en campo?', options: ['0 °C', '5 °C', '15 °C', '25 °C'], correctAnswer: 1, explanation: 'Por debajo de 5 °C el polietileno pierde flexibilidad y puede agrietarse al doblar durante la instalación.' },
            { questionText: '¿Cuál es la cobertura mínima en cruce de carretera pavimentada?', options: ['600 mm', '900 mm', '1200 mm', '1500 mm'], correctAnswer: 2, explanation: 'En cruces de carreteras pavimentadas o vías férreas se requiere cobertura mínima de 1200 mm.' },
            { questionText: '¿A qué presión se realiza la prueba hidrostática de campo para sistemas RTP nuevos?', options: ['1.0 × NWP', '1.25 × NWP', '1.5 × NWP', '2.0 × NWP'], correctAnswer: 1, explanation: 'API RP 15S establece FHTP = 1.25 × NWP para sistemas instalados nuevos.' },
            { questionText: '¿Cuál es el criterio de aceptación de la prueba hidrostática de campo?', options: ['Caída máx. del 5% en 4 horas', 'Caída máx. del 1% en la última hora (corregida por temperatura)', 'Presión constante absoluta sin ninguna caída', 'Caída máx. del 2% en toda la prueba'], correctAnswer: 1, explanation: 'La variación de presión corregida por temperatura no debe superar el 1% de Pt en la última hora de prueba.' },
            { questionText: '¿Por qué es crítico purgar el aire antes de la prueba hidrostática?', options: ['Para reducir consumo de agua', 'Porque el aire comprime y puede enmascarar fugas o generar golpe de ariete', 'Para aumentar la presión de prueba', 'Porque el oxígeno oxida el fitting'], correctAnswer: 1, explanation: 'El aire atrapado comprime y puede enmascarar fugas o causar golpe de ariete al despresurizar.' },
            { questionText: '¿Cuánto tiempo mínimo de estabilización al 50% de Pt antes de continuar?', options: ['5 min', '15 min', '30 min', '60 min'], correctAnswer: 2, explanation: 'Se mantiene al 50% de Pt durante 30 minutos para estabilización térmica del sistema.' },
            { questionText: '¿Cuál es el espesor mínimo de cama de arena bajo el RTP?', options: ['50 mm', '75 mm', '100 mm', '200 mm'], correctAnswer: 2, explanation: 'Se requiere cama de arena limpia de 100 mm mínimo bajo la generatriz inferior del RTP.' },
            { questionText: '¿Cuánto dura el período de registro oficial de presión en sistemas ≤ 10 km?', options: ['1 hora', '2 horas', '4 horas', '8 horas'], correctAnswer: 2, explanation: 'Para sistemas de hasta 10 km, el período oficial de prueba es mínimo 4 horas con registro cada 15 minutos.' },
            { questionText: '¿Cómo debe izarse correctamente un carrete de RTP?', options: ['Cable de acero central', 'Una sola eslinga textil central', 'Eslingas textiles de 4 puntos distribuidos', 'Montacargas sin eslingas'], correctAnswer: 2, explanation: 'Se usan eslingas textiles de 4 puntos para distribuir la carga. Un punto central genera flexión concentrada.' },
            { questionText: '¿Qué riesgo genera la despresurización brusca del RTP tras la prueba?', options: ['Aumento de temperatura', 'Colapso del liner por presión negativa (vacío)', 'Oxidación del refuerzo de aramida', 'Deformación de los fittings'], correctAnswer: 1, explanation: 'La despresurización brusca puede crear vacío interno que colapsa el liner de HDPE; siempre despresurizar lentamente.' },
          ],
        },
      },
      {
        order: 5, isPremium: false, passingScore: 70,
        title: 'API RP 15SIH — Los 5 Métodos de Instalación del RTP',
        description: 'Planificación de ruta, los cinco métodos de instalación (zanja, HDD, arado, pull-through y superficie) y uniones de campo según API RP 15SIH Secciones 6 y 7.',
        lessons: [
          { order: 1, title: 'Planificación de ruta — API RP 15SIH Sección 6',
            content: '## 🗺️ Layout planning — Antes de instalar\n\nLa Sección 6 de API RP 15SIH exige definir y documentar la ruta **antes** de cualquier movimiento de tierra.\n\n---\n\n## 📐 Parámetros de diseño clave\n\n| Factor | Requisito |\n|---|---|\n| Radio mínimo de curvatura | ≥ **MBR** del fabricante (siempre en frío) |\n| Temperatura de operación | No superar temperatura calificada del liner |\n| Pipe locators | Requeridos para identificar el trazado enterrado |\n\n---\n\n## 🚧 Zonas críticas a documentar en el plano de ruta\n\n- 🔄 **Cambios de dirección** — verificar que el radio ≥ MBR\n- 🛣️ **Cruces de caminos y vías** — cobertura mínima y método de cruce\n- 🏗️ **Risers y conexiones superficiales** — transición tubo-superficie\n- 🌊 **Cruces de cauces** — profundidad y método (HDD o casing)\n- 📍 **Pipe locators** — sistema pasivo o activo a lo largo de todo el trazado\n\n---\n\n## 📋 Documentos de ruta requeridos\n\n- ✅ Plano con coordenadas GPS o datum de campo\n- ✅ Tabla de cruces (método + cobertura por cada cruce)\n- ✅ Profundidad especificada por zona\n- ✅ Lista de fittings y accesorios por punto' },
          { order: 2, title: 'Los 5 métodos de instalación — API RP 15SIH Sección 7.3',
            content: '## ⚙️ Los 5 métodos de instalación del RTP\n\n---\n\n### 1️⃣ Zanja y relleno — Trench & Backfill (7.3.1)\n- Excavación con retroexcavadora + cama de arena 100 mm\n- Relleno por capas compactadas\n- 🟢 **Ideal para:** rutas largas en terreno accesible\n\n### 2️⃣ Perforación direccional — HDD / Boring (7.3.2)\n- Máquina de perforación horizontal direccional\n- Sin apertura de zanja en superficie\n- 🟢 **Ideal para:** cruces de carreteras, ríos y zonas urbanas\n\n### 3️⃣ Arado — Plowing (7.3.3)\n- Reja de arado abre y cierra el terreno en una sola pasada\n- Velocidad de instalación muy alta\n- 🟢 **Ideal para:** terreno agrícola sin obstáculos subterráneos\n\n### 4️⃣ Tiro a través de tubería existente — Pull-through (7.3.4)\n- El RTP se inserta dentro de un ducto viejo fuera de servicio\n- No requiere excavación\n- 🟢 **Ideal para:** rehabilitación de líneas sin interrumpir la superficie\n\n### 5️⃣ Superficie — Surface lay (7.3.5)\n- Tubo tendido sobre el terreno con soportes o anclajes\n- 🟢 **Ideal para:** instalaciones temporales o áreas remotas\n\n---\n\n## 📦 Desenrollado (Sección 7.2)\n\n> El carrete debe desenrollarse en la **dirección de enrollado original**.\n> Invertir la dirección puede dañar el refuerzo helicoidal.' },
          { order: 3, title: 'Uniones de campo y registros — API RP 15SIH Secciones 7.4 y 10',
            content: '## 🔗 Uniones en campo — Sección 7.4\n\n| Tipo de unión | Procedimiento |\n|---|---|\n| **Fitting de compresión** | Seguir FIP del fabricante con herramienta hidráulica |\n| **Electrofusión** | Equipo calificado + control de temperatura |\n| **Roscado / Bridado** | Para conexión a manifolds y equipos de acero |\n\n### ⚠️ Requisitos críticos de campo\n\n- 🚫 No improvisar adaptaciones fuera del FIP\n- 🌡️ Temperatura ambiental durante la unión: **> 5 °C**\n- 🧹 Limpiar extremos con **alcohol isopropílico**\n- 📏 Verificar inserción completa hasta el **tope del fitting**\n\n---\n\n## 📁 Registros obligatorios — Sección 10\n\n| Documento | Contenido mínimo |\n|---|---|\n| **Levantamiento de ruta** | GPS / coordenadas del trazado instalado |\n| **Planos as-built** | Fittings, válvulas y accesorios |\n| **Registro de fittings** | ID, operador, fecha, resultado |\n| **Inspección de recepción** | Tabla 1 de 15SIH |\n| **Registros de prueba** | Presión, temperatura, duración, resultado |\n\n> 📌 Todos los registros deben conservarse durante **toda la vida útil** de la instalación.' },
        ],
        quiz: {
          title: 'Evaluación M5 — Instalación API RP 15SIH',
          questions: [
            { questionText: '¿Cuántos métodos de instalación define API RP 15SIH Sección 7.3?', options: ['3 métodos', '4 métodos', '5 métodos', '7 métodos'], correctAnswer: 2, explanation: 'La Sección 7.3 de API RP 15SIH define 5 métodos: zanja/relleno, HDD/boring, arado, pull-through y superficie.' },
            { questionText: '¿Qué método de instalación se usa para cruzar una carretera sin abrir la superficie?', options: ['Zanja y relleno', 'Perforación horizontal dirigida (HDD)', 'Arado (Plowing)', 'Superficie (Surface lay)'], correctAnswer: 1, explanation: 'El HDD (Horizontal Directional Drilling) permite instalar el tubo bajo cruces sin excavación en superficie.' },
            { questionText: '¿En qué dirección debe desenrollarse el carrete RTP según la Sección 7.2?', options: ['En cualquier dirección', 'En la dirección de enrollado original', 'En dirección contraria al enrollado', 'Depende del diámetro'], correctAnswer: 1, explanation: 'Invertir la dirección de desenrollado puede dañar el refuerzo helicoidal; siempre en la dirección original.' },
            { questionText: '¿Qué método de instalación es ideal para rehabilitar una línea vieja sin excavar?', options: ['Zanja y relleno', 'Arado (Plowing)', 'Pull-through (tiro dentro de tubería existente)', 'Superficie (Surface lay)'], correctAnswer: 2, explanation: 'El pull-through inserta el RTP nuevo dentro del ducto viejo fuera de servicio, sin necesidad de excavación.' },
            { questionText: '¿Cuál es la temperatura mínima para realizar uniones de campo según API RP 15SIH?', options: ['0 °C', '> 5 °C', '> 15 °C', '> 25 °C'], correctAnswer: 1, explanation: 'La temperatura ambiental durante la instalación de fittings debe ser superior a 5 °C para garantizar la integridad del liner.' },
            { questionText: '¿Qué método de instalación tiene la mayor velocidad de ejecución en terreno agrícola plano?', options: ['HDD', 'Zanja y relleno', 'Arado (Plowing)', 'Pull-through'], correctAnswer: 2, explanation: 'El arado abre y cierra el terreno en una sola pasada continua, siendo el método de mayor velocidad en terreno agrícola.' },
            { questionText: '¿Qué sección de API RP 15SIH cubre la planificación de ruta?', options: ['Sección 5', 'Sección 6', 'Sección 7', 'Sección 9'], correctAnswer: 1, explanation: 'La Sección 6 cubre el diseño de layout: radios de curvatura, cruces, risers y pipe locators.' },
            { questionText: '¿Qué sistema requiere la Sección 6 de API RP 15SIH para identificar el trazado enterrado?', options: ['Marcas de pintura en superficie', 'Pipe locators (activos o pasivos)', 'Señalización vertical cada 50 m', 'GPS continuo del operador'], correctAnswer: 1, explanation: 'API RP 15SIH exige instalar pipe locators para poder identificar y localizar el trazado enterrado en campo.' },
            { questionText: '¿Qué documento recoge la ubicación real de fittings y válvulas instaladas?', options: ['Product Data Sheet (PDS)', 'Mill Certificate', 'Planos as-built', 'Type Test Report'], correctAnswer: 2, explanation: 'Los planos as-built documentan la ubicación real de fittings, válvulas y accesorios según la Sección 10 de 15SIH.' },
            { questionText: '¿Cuánto tiempo deben conservarse los registros de instalación según API RP 15SIH?', options: ['5 años', '10 años', 'Mientras esté vigente la garantía', 'Toda la vida útil de la instalación'], correctAnswer: 3, explanation: 'Los registros de instalación deben conservarse durante toda la vida útil de la instalación para trazabilidad e integridad.' },
          ],
        },
      },
      {
        order: 6, isPremium: false, passingScore: 70,
        title: 'API RP 15SIH — Inspección Post-instalación, Pruebas y Registros',
        description: 'Inspección visual en dos etapas (Sección 8), prueba hidrostática y de anular (Sección 9), y documentación as-built obligatoria (Sección 10) según API RP 15SIH.',
        lessons: [
          { order: 1, title: 'Inspección post-instalación — API RP 15SIH Sección 8',
            content: '## 🔍 Inspección en 2 etapas — Sección 8\n\n---\n\n### 8.1 — Después del desenrollado (antes de instalar fittings)\n\nInspección visual obligatoria del tramo:\n\n- 👁️ Daño mecánico en jacket (cortes, abrasiones profundas)\n- ↩️ Kinking — curvado por debajo del **MBR**\n- 🔵 Ovalización excesiva del diámetro\n- 🌡️ Deformación del jacket por calor\n\n> ⚠️ Registrar y marcar todo daño. No instalar tramos dañados sin aprobación escrita del fabricante.\n\n---\n\n### 8.2 — Después de instalar fittings (antes de enterrar)\n\n| Verificación | ¿Qué revisar? |\n|---|---|\n| Fittings | Inserción completa, sin movimiento, sin fuga |\n| Alineación | Sin flexión anormal en el cuerpo del fitting |\n| Registro | Cada fitting en el dossier de campo |\n| Accesibilidad | Puntos de prueba accesibles antes del relleno |' },
          { order: 2, title: 'Pruebas antes de puesta en servicio — API RP 15SIH Sección 9',
            content: '## 🧪 Pruebas requeridas — Sección 9\n\n---\n\n### 💧 9.1 Prueba hidrostática\n\n| Parámetro | Valor |\n|---|---|\n| Presión de prueba | **≥ 1.25 × MOP** (sin exceder 100% NPR) |\n| Fluido | Agua limpia, sin partículas |\n| Criterio | Sin caída de presión ni fuga visible |\n\n---\n\n### 🔵 9.2 Prueba del anular (Annulus test)\n\nSi el diseño incluye monitoreo del anular:\n\n- Presurizar el anular con **nitrógeno** a baja presión\n- Mantener y verificar que no hay caída de presión\n- ✅ Confirma integridad del **liner y del jacket** antes de enterrar\n\n---\n\n### 🛡️ 9.3 Prevención de corrosión\n\nPara RTP con refuerzo de acero enterrado:\n\n- ✅ Anular con vent abierto — evita acumulación de humedad\n- ✅ Inspección de end fittings metálicos antes de enterrar\n- ✅ Recubrimiento anticorrosivo en partes metálicas expuestas' },
          { order: 3, title: 'Documentación as-built obligatoria — API RP 15SIH Sección 10',
            content: '## 📁 Documentación as-built — Sección 10\n\nUna instalación RTP no está completa sin su **dossier de registros**.\n\n---\n\n## 📋 Documentos requeridos\n\n| Documento | Contenido mínimo |\n|---|---|\n| **Levantamiento de ruta** | Coordenadas GPS del trazado real instalado |\n| **Planos as-built** | Ubicación de fittings, válvulas y accesorios |\n| **Registro de fittings de campo** | N° de unión, operador, fecha, resultado |\n| **Inspección de recepción** | Resultados de la Tabla 1 de 15SIH |\n| **Registros de prueba** | Presión, temperatura, duración y resultado |\n\n---\n\n## 🔑 ¿Por qué son críticos los registros?\n\n- 🔍 Permiten rastrear la causa de una falla futura\n- 📜 Son requisito para reclamaciones de **garantía** al fabricante\n- 🔄 Son la base del programa de **inspección en operación**\n- 🏛️ Reguladores y auditores pueden solicitarlos en cualquier momento\n\n> 📌 Los registros deben conservarse durante **toda la vida útil** de la instalación.' },
        ],
        quiz: {
          title: 'Evaluación M6 — Post-instalación y Pruebas API RP 15SIH',
          questions: [
            { questionText: '¿Cuántas etapas de inspección post-instalación define la Sección 8 de API RP 15SIH?', options: ['1 etapa', '2 etapas', '3 etapas', '4 etapas'], correctAnswer: 1, explanation: 'La Sección 8 define 2 etapas: 8.1 después del desenrollado y 8.2 después de instalar fittings, antes de enterrar.' },
            { questionText: '¿Qué se verifica en la inspección 8.1 de API RP 15SIH?', options: ['Registro final as-built', 'Daño mecánico, kinking, ovalización y deformación por calor del tramo desenrollado', 'Presión de prueba hidrostática', 'Calidad del relleno de zanja'], correctAnswer: 1, explanation: 'La inspección 8.1 verifica daño mecánico en jacket, kinking (sobre-curvado), ovalización excesiva y daño térmico.' },
            { questionText: '¿Cuál es la presión mínima de prueba hidrostática según la Sección 9 de API RP 15SIH?', options: ['1.0 × MOP', '1.1 × MOP', '1.25 × MOP (sin exceder 100% NPR)', '1.5 × MOP'], correctAnswer: 2, explanation: 'La Sección 9 establece presión de prueba ≥ 1.25 × MOP sin exceder el 100% de la presión nominal del producto (NPR).' },
            { questionText: '¿Con qué fluido se realiza la prueba del anular (Sección 9.2)?', options: ['Agua a presión de operación', 'Nitrógeno a baja presión', 'Gas del proceso a MOP', 'Aceite dieléctrico'], correctAnswer: 1, explanation: 'La prueba del anular se realiza con nitrógeno a baja presión para verificar hermeticidad del liner y jacket antes de enterrar.' },
            { questionText: '¿Qué confirma la prueba del anular (annulus test) de la Sección 9.2?', options: ['La resistencia axial del fitting', 'La integridad del liner y del jacket antes de enterrar', 'El radio mínimo de curvatura', 'El torque de apriete del fitting'], correctAnswer: 1, explanation: 'La prueba del anular con nitrógeno confirma que el liner y el jacket están íntegros, sin vías de comunicación antes de enterrar.' },
            { questionText: '¿Qué documento registra la ubicación real de fittings y válvulas según la Sección 10?', options: ['Product Data Sheet (PDS)', 'Type Test Report', 'Planos as-built', 'Mill Certificate'], correctAnswer: 2, explanation: 'Los planos as-built documentan la ubicación real (GPS) de fittings, válvulas y accesorios instalados.' },
            { questionText: '¿Cuándo es obligatorio el recubrimiento anticorrosivo según la Sección 9.3?', options: ['En todas las instalaciones sin excepción', 'Solo en RTP con refuerzo de acero con partes metálicas expuestas', 'Solo en instalaciones offshore', 'Solo si el fluido contiene H₂S'], correctAnswer: 1, explanation: 'La Sección 9.3 aplica recubrimiento anticorrosivo en fittings y partes metálicas expuestas cuando el RTP tiene refuerzo de acero.' },
            { questionText: '¿Qué acción debe tomarse si se detecta daño en el tramo durante la inspección 8.1?', options: ['Instalar igualmente y monitorear', 'Registrar, marcar el tramo y no instalar sin aprobación escrita del fabricante', 'Reparar con cinta adhesiva de campo', 'Ignorar si el daño es solo en el jacket'], correctAnswer: 1, explanation: 'Todo daño debe registrarse y marcarse. El tramo no debe instalarse sin aprobación escrita del fabricante.' },
            { questionText: '¿Por qué los registros de instalación de la Sección 10 son críticos para la garantía?', options: ['Solo para cumplimiento normativo', 'Porque permiten rastrear la causa de fallas y son requisito para reclamaciones al fabricante', 'Solo para auditorías gubernamentales', 'Solo para el seguro de la instalación'], correctAnswer: 1, explanation: 'Los registros de la Sección 10 son la base de la trazabilidad, son requisito para reclamaciones de garantía y pueden ser solicitados por reguladores.' },
            { questionText: '¿Qué fluido se usa en la prueba hidrostática según la Sección 9.1?', options: ['Fluido del proceso', 'Gas nitrógeno', 'Agua limpia sin partículas', 'Aceite mineral calificado'], correctAnswer: 2, explanation: 'La prueba hidrostática se realiza con agua limpia sin partículas para evitar daño al liner y garantizar lectura de presión precisa.' },
          ],
        },
      },
      {
        order: 7, isPremium: false, passingScore: 70,
        title: 'API RP 15SA — Gestión de Integridad: Ciclo PDCA y Amenazas',
        description: 'El Integrity Management Program (IMP) con sus 15 elementos, el ciclo PDCA, y las tablas de amenazas del tubo (Tabla 1) y componentes del sistema (Tabla 2) según API RP 15SA 1ª edición 2022.',
        lessons: [
          { order: 1, title: 'El programa IMP y el ciclo PDCA — API RP 15SA',
            content: '## 🔄 API RP 15SA — Gestión de Integridad (1ª ed. febrero 2022)\n\nAplica el ciclo **PDCA** a sistemas RTP spoolable en operación continua.\n\n---\n\n## 📋 Los 4 ejes del ciclo PDCA\n\n| Eje | Contenido |\n|---|---|\n| **P** — Planificar | Política, organización, amenazas, evaluación de riesgos |\n| **D** — Hacer | Inspecciones, monitoreo, reparaciones, intervenciones |\n| **C** — Verificar | Análisis de resultados, KPIs, revisión de incidentes |\n| **A** — Actuar | Mejora continua y actualización del IMP |\n\n---\n\n## 🧱 Los 15 elementos del IMP (Figura 1 de la norma)\n\n- 🏢 Política de integridad + Roles y responsabilidades\n- ⚠️ Identificación de amenazas + Evaluación de riesgos\n- 📐 Criterios de aceptación + Programa de inspección\n- 🔧 Respuesta a emergencias + Gestión de cambios\n- 📊 Análisis de incidentes + Gestión de contratistas\n- 📁 Gestión documental + Comunicación interna\n- 🔄 Revisión gerencial + Mejora continua del programa\n\n> 📌 El IMP debe estar **documentado y aprobado** antes de la puesta en operación del sistema.' },
          { order: 2, title: 'Tabla 1 — Amenazas del tubo RTP (API RP 15SA)',
            content: '## ⚠️ Tabla 1 — Amenazas del RTP por componente\n\n---\n\n### 🔵 1. Liner (1.1 — 1.6)\n\n| ID | Amenaza |\n|---|---|\n| 1.1 | Daño mecánico (instalación o excavación de terceros) |\n| 1.2 | Degradación química (fluido incompatible con el liner) |\n| 1.3 | Permeación de gases (H₂S/CO₂ acumulados en el anular) |\n| 1.4 | Blistering por descompresión rápida (blow-down) |\n| 1.5 | Daño por temperatura fuera del rango calificado |\n| 1.6 | Envejecimiento y degradación UV en tramos expuestos |\n\n---\n\n### 🔶 2. Refuerzo estructural (2.1 — 2.5)\n\n| ID | Amenaza |\n|---|---|\n| 2.1 | Daño mecánico externo (aplastamiento, impacto) |\n| 2.2 | Fatiga por ciclos de presión excesivos |\n| 2.3 | Tensión axial fuera del MTAL calificado |\n| 2.4 | SSC del refuerzo de acero (H₂S en el anular) |\n| 2.5 | Sobre-curvado por debajo del MBR |\n\n---\n\n### 🟢 3. Cubierta exterior y 4. Fittings de campo\n\n| ID | Amenaza |\n|---|---|\n| 3.1 | Daño mecánico al jacket — exposición del refuerzo |\n| 4.1 | Instalación incorrecta del fitting |\n| 4.2 | Fitting de diámetro o tipo no calificado |\n| 4.3 | Daño mecánico en el cuerpo del fitting |\n| 4.4 | Corrosión de componentes metálicos del fitting |' },
          { order: 3, title: 'Tabla 2 — Amenazas de componentes del sistema (API RP 15SA)',
            content: '## ⚠️ Tabla 2 — Amenazas por componente del sistema instalado\n\n---\n\n### 🏗️ 1. Risers (1.1 — 1.3)\n- Daño por impacto vehicular o de equipos en tramo aéreo\n- Fatiga por vibración inducida (viento o flujo interno)\n- Degradación UV en tramo aéreo sin protección\n\n### ⚙️ 2. Conexiones de acero — Steel risers (2.1 — 2.5)\n- Corrosión galvánica en la transición acero-HDPE\n- Pérdida de hermeticidad en la unión de transición\n- Movimiento diferencial por expansión térmica\n\n### 🛣️ 3. Cruces de caminos — Road crossings (3.1 — 3.2)\n- Cobertura insuficiente por erosión o remoción de suelo\n- Daño por carga de tráfico sobre tramo sin casing\n\n### ⚡ 4. Protección catódica (4.1 — 4.3)\n- Solo aplica si el sistema incluye fittings de acero enterrados\n- Verificar que la CP no interfiere con el liner de HDPE\n\n### 🌊 5-7. Vanos libres, relleno y trazado\n\n| ID | Amenaza |\n|---|---|\n| **5.1 Free spans** | Tramo sin apoyo → flexión sostenida y fatiga |\n| **6.1-6.2 Backfill** | Relleno agresivo o sin cama de arena |\n| **7.1-7.3 Pipe layout** | Curvado excesivo o anclajes no previstos |' },
        ],
        quiz: {
          title: 'Evaluación M7 — Gestión de Integridad RTP',
          questions: [
            { questionText: '¿Cuál es la principal causa estadística de falla en sistemas RTP enterrados?', options: ['Corrosión interna del liner', 'Daño por interferencia de terceros (excavación)', 'Degradación UV del jacket', 'Colapso por vacío'], correctAnswer: 1, explanation: 'La interferencia de terceros es estadísticamente la principal causa de falla en sistemas de tubería enterrada incluyendo RTP.' },
            { questionText: '¿Cuál es la frecuencia mínima recomendada de inspección del ROW en líneas de alta presión?', options: ['Mensual', 'Trimestral', 'Semestral', 'Anual'], correctAnswer: 2, explanation: 'La práctica de la industria recomienda inspección visual del ROW con frecuencia mínima semestral para líneas de alta presión.' },
            { questionText: '¿Qué KPI es el más utilizado para medir el desempeño de integridad de un sistema de tuberías?', options: ['Presión de operación promedio', 'Número de fugas por 100 km-año', '% de utilización de capacidad', 'Número de conexiones por km'], correctAnswer: 1, explanation: 'El número de fugas por 100 km-año es el KPI de integridad más utilizado para comparar sistemas de tuberías.' },
            { questionText: '¿Qué acción inmediata se requiere ante fuga activa en un sistema RTP?', options: ['Reducir presión al 50% y continuar', 'Despresurizar inmediatamente y aislar con válvulas de bloqueo', 'Aumentar inhibidor de corrosión', 'Esperar la próxima parada programada'], correctAnswer: 1, explanation: 'Ante fuga activa: despresurización inmediata y aislamiento del tramo con válvulas de bloqueo.' },
            { questionText: '¿Cuándo puede repararse un daño en el jacket exterior SIN despresurizar?', options: ['Siempre', 'Solo si el daño no afecta la capa de refuerzo', 'Solo si presión < 50% NWP', 'Nunca sin despresurizar'], correctAnswer: 1, explanation: 'Si el daño se confirma limitado al jacket sin afectar el refuerzo, puede repararse con kit del fabricante sin despresurizar.' },
            { questionText: '¿Por qué no aplican directamente los métodos FFS genéricos (API 579) al RTP dañado?', options: ['Porque API 579 no cubre sistemas subterráneos', 'Porque el RTP es un material compuesto anisótropo, no un metal homogéneo', 'Porque API 579 no es reconocido en la industria', 'Porque el RTP no tiene defectos superficiales'], correctAnswer: 1, explanation: 'API 579 está desarrollado para metales homogéneos isótropos. El RTP es un material compuesto anisótropo con comportamiento diferente.' },
            { questionText: '¿Cuánto puede superar la temperatura máxima calificada antes de activar el retiro de servicio?', options: ['> 2 °C', '> 5 °C', '> 10 °C', '> 20 °C'], correctAnswer: 1, explanation: 'Si la temperatura excede la máxima calificada en más de 5 °C, se debe iniciar el retiro de servicio.' },
            { questionText: '¿Qué prueba debe realizarse sobre el tramo reparado antes de retornar a operación?', options: ['Solo inspección visual', 'Solo prueba neumática', 'Prueba hidrostática 1.25 × NWP durante 4 horas', 'Solo medición dimensional'], correctAnswer: 2, explanation: 'Tras reparación, el tramo se somete a prueba hidrostática a 1.25 × NWP durante 4 horas antes de retornar a servicio.' },
            { questionText: '¿Cuánto tiempo acumulado de operación > 110% NWP activa el criterio de retiro?', options: ['15 minutos', '30 minutos', '1 hora acumulada', '4 horas acumuladas'], correctAnswer: 2, explanation: 'Operación por encima del 110% de NWP por más de 1 hora acumulada activa el criterio de retiro automático.' },
            { questionText: '¿Qué amenaza puede generar SSC en el alambre de refuerzo de acero?', options: ['Sobrepresión operacional', 'Permeación de H₂S al anular en servicio sour', 'Exposición UV en superficie', 'Ciclos de temperatura'], correctAnswer: 1, explanation: 'El H₂S que permea el liner y se acumula en el anular puede causar Sulfide Stress Cracking (SSC) en el refuerzo de acero.' },
          ],
        },
      },
      {
        order: 8, isPremium: false, passingScore: 70,
        title: 'API RP 15SA — Evaluación de Integridad: 13 Métodos y Reparación',
        description: 'Los 13 métodos de evaluación de integridad de la Tabla 3, el método estándar de reparación por corte y reemplazo (Sección 10), y los KPIs del programa según API RP 15SA.',
        lessons: [
          { order: 1, title: 'Programa de evaluación de integridad — API RP 15SA Sección 8',
            content: '## 🔬 Evaluación de integridad — Por qué y cuándo\n\nLa evaluación es el núcleo del eje **Verificar (C)** del ciclo PDCA de 15SA.\n\n---\n\n## 🎯 Objetivos\n\n- ✅ Detectar amenazas de Tabla 1 y Tabla 2 **antes** de que causen falla\n- ✅ Establecer condición base (*baseline*) de la instalación\n- ✅ Determinar frecuencia de inspección según nivel de riesgo\n- ✅ Generar datos para análisis de tendencias a largo plazo\n\n---\n\n## 📅 ¿Qué factores aumentan la frecuencia de evaluación?\n\n| Factor | Impacto |\n|---|---|\n| Alta presión de operación | Mayor frecuencia |\n| Fluido con H₂S o CO₂ | Monitoreo de anular más seguido |\n| Historial de incidentes | Inspección intensificada |\n| Antigüedad > 10 años | Evaluación exhaustiva |\n\n---\n\n## 📋 Revisión documental (Sección 5) — Primer paso\n\nAntes de cualquier inspección de campo, revisar:\n\n- Planos as-built y registros de instalación\n- Historial de operación (presiones, temperaturas, fluidos)\n- Registros de mantenimiento e incidentes previos\n- Resultados de evaluaciones anteriores' },
          { order: 2, title: 'Tabla 3 — Los 13 métodos de evaluación de integridad',
            content: '## 🔎 Tabla 3 de API RP 15SA — 13 métodos de evaluación\n\n---\n\n### 👁️ Métodos de inspección externa\n\n| # | Método | ¿En operación? |\n|---|---|---|\n| 1 | **Inspección visual** — jacket, risers, fittings | ✅ Sí |\n| 2 | **Levantamiento aéreo** — dron o helicóptero | ✅ Sí |\n| 3 | **Georradar (GPR)** — cobertura y desplazamientos | ✅ Sí |\n| 4 | **Termografía** — fugas y anomalías térmicas | ✅ Sí |\n\n---\n\n### 🔵 Métodos del anular\n\n| # | Método | ¿En operación? |\n|---|---|---|\n| 5 | **Monitoreo de presión del anular** | ✅ Sí |\n| 6 | **Monitoreo de volumen y composición del anular** | ✅ Sí |\n\n---\n\n### 💧 Pruebas de presión\n\n| # | Método | ¿En operación? |\n|---|---|---|\n| 7 | **Hidrotest** ≥ 1.25 × MOP, ≤ 100% NPR | ❌ Parada requerida |\n\n---\n\n### 🔩 Métodos de inspección no destructiva (NDT)\n\n| # | Método | ¿En operación? |\n|---|---|---|\n| 8 | **CCTV interno** — cámara en el liner | ❌ Parada |\n| 9 | **Ultrasonido (UT)** — espesor y daños de liner | Parcial |\n| 10 | **Radiografía** — refuerzo y fittings | ❌ Parada |\n| 11 | **Inspección de fittings** y conexiones | Parcial |\n| 12 | **Close Interval Survey (CIS)** — CP de fittings | ✅ Sí |\n| 13 | **Evaluación de recubrimiento** de fittings | Parcial |' },
          { order: 3, title: 'Reparación y evaluación del programa — API RP 15SA Secciones 10 y 11',
            content: '## 🔧 Reparación — Sección 10\n\nAPI RP 15SA define un único método de reparación calificado:\n\n### ✂️ Corte y reemplazo (Cutout & Replacement)\n\n| Paso | Acción |\n|---|---|\n| 1️⃣ | Despresurizar y aislar el tramo con válvulas de bloqueo |\n| 2️⃣ | Localizar exactamente el daño (visual o NDT) |\n| 3️⃣ | Cortar el tramo dañado con sierra de banda — cortes ⊥ |\n| 4️⃣ | Instalar fittings de terminación en ambos extremos |\n| 5️⃣ | Insertar tramo nuevo con fittings de acoplamiento |\n| 6️⃣ | Hidrotest del tramo reparado: ≥ 1.25 × MOP |\n| 7️⃣ | Documentar la reparación en el historial de integridad |\n\n> ⚠️ No existe reparación de "parchado" calificada. La única opción válida es el **reemplazo del tramo**.\n\n---\n\n## 📊 KPIs del programa — Sección 11\n\n| Indicador | ¿Qué mide? |\n|---|---|\n| Fugas / 100 km-año | Tasa de fallas del sistema |\n| % inspecciones completadas en plazo | Cumplimiento del IMP |\n| Excursiones operacionales registradas | Sobrepresiones / sobretemperaturas |\n| Tiempo de respuesta a emergencias | Eficiencia de la organización |\n\n> 🔄 El IMP debe revisarse **anualmente** como mínimo, o tras cualquier incidente significativo.' },
        ],
        quiz: {
          title: 'Evaluación M8 — RTP en Ambiente Marino',
          questions: [
            { questionText: '¿Por qué el RTP de HDPE no requiere protección catódica en ambiente marino?', options: ['Porque siempre está enterrado', 'Porque el jacket de HDPE es polímero no metálico, inmune a corrosión electroquímica', 'Porque el agua de mar no es corrosiva para el polietileno', 'Porque la corriente marina evita la corrosión'], correctAnswer: 1, explanation: 'El HDPE es un polímero dieléctrico no metálico. La corrosión electroquímica solo afecta metales; el jacket de HDPE no la sufre.' },
            { questionText: '¿Qué fenómeno genera vibración en el RTP cuando la corriente marina supera el umbral crítico?', options: ['Golpe de ariete (water hammer)', 'Vibración por Vórtices (VIV — Vortex Induced Vibration)', 'Cavitación interna', 'Resonancia acústica'], correctAnswer: 1, explanation: 'Las corrientes por encima del umbral crítico inducen desprendimiento de vórtices alternados que generan VIV.' },
            { questionText: '¿Por qué el RTP tiene flotabilidad positiva en agua de mar?', options: ['Porque contiene gas atrapado', 'Porque la densidad del HDPE (≈0.95 g/cm³) es menor que la del agua de mar (≈1.025 g/cm³)', 'Porque el refuerzo de aramida flota', 'Porque el Carbon Black reduce la densidad'], correctAnswer: 1, explanation: 'El HDPE tiene densidad ≈0.95 g/cm³, menor al agua de mar (≈1.025 g/cm³), generando flotabilidad positiva neta.' },
            { questionText: '¿Cuál es el factor de estabilidad on-bottom mínimo recomendado para RTP con peso de concreto?', options: ['1.0 × densidad agua de mar', '1.10 × densidad agua de mar', '1.25 × densidad agua de mar', '1.5 × densidad agua de mar'], correctAnswer: 1, explanation: 'La densidad del conjunto CWC + RTP debe ser ≥ 1.10 × densidad del agua de mar para estabilidad on-bottom.' },
            { questionText: '¿Qué espesor mínimo de revestimiento de caucho se recomienda en splash zone?', options: ['2 mm', '4 mm', '6 mm', '10 mm'], correctAnswer: 2, explanation: 'Se recomienda revestimiento de caucho o neopreno de al menos 6 mm de espesor en la splash zone.' },
            { questionText: '¿Qué profundidad mínima requiere el casing en un beach crossing?', options: ['Sobre el lecho marino', '1 m bajo el lecho marino', '3-5 m bajo la profundidad de acción del oleaje', 'Solo en la línea de costa'], correctAnswer: 2, explanation: 'El casing debe enterrarse 3-5 m por debajo de la profundidad de acción de las olas para evitar exposición por erosión.' },
            { questionText: '¿Cuál es la concentración de sales del agua de mar estándar?', options: ['5 g/L', '15 g/L', '35 g/L', '70 g/L'], correctAnswer: 2, explanation: 'El agua de mar estándar contiene aproximadamente 35 g/L de sales disueltas (salinidad de 35 ppt).' },
            { questionText: '¿Qué configuración geométrica absorbe movimientos dinámicos de plataformas flotantes?', options: ['Línea recta tensa (taut)', 'Vertical (vertical riser)', 'Lazy-wave o S-lay', 'Espiral helicoidal'], correctAnswer: 2, explanation: 'La configuración lazy-wave crea una reserva de longitud en catenaria que absorbe los movimientos de la plataforma sin exceder el MBR.' },
            { questionText: '¿Con qué frecuencia se recomienda inspección visual en splash zone los primeros 2 años?', options: ['Anual', 'Semestral', 'Trimestral', 'Mensual'], correctAnswer: 3, explanation: 'Durante los primeros 2 años, la inspección visual mensual en splash zone verifica la integridad del revestimiento anti-fatiga.' },
            { questionText: '¿Qué parámetro crítico debe verificarse en el diseño lazy-wave del RTP?', options: ['Que el diámetro interior sea constante', 'Que la temperatura del agua de mar < 32 °C', 'Que la configuración dinámica nunca exceda el MBR', 'Que el color del jacket sea visible'], correctAnswer: 2, explanation: 'En el diseño lazy-wave, el parámetro crítico es que bajo cualquier condición dinámica el radio de curvatura no sea inferior al MBR.' },
          ],
        },
      },
      {
        order: 9, isPremium: true, passingScore: 85,
        title: 'API 17J — Líneas Flexibles Submarinas de Aguas Profundas',
        description: 'MÓDULO PREMIUM — Diseño, calificación y gestión de integridad de tuberías flexibles no pegadas (unbonded) para aplicaciones subsea y deep water según API Spec 17J / ISO 13628-2.',
        lessons: [
          { order: 1, title: 'Alcance de API 17J y arquitectura del flexible submarino',
            content: '## 🌊 API Spec 17J — Flexible Pipe para Subsea\n\nIdéntica a **ISO 13628-2**. Cubre flowlines, risers y jumpers hasta **3,000 m** de profundidad.\n\n---\n\n## 🏗️ Arquitectura — Capas del flexible submarino\n\n| # | Capa | Material | Función |\n|---|---|---|---|\n| 1 | **Carcass** | Acero inox 316L / Duplex | Anti-colapso por presión hidrostática externa |\n| 2 | **Pressure sheath** | HDPE / PA12 / PA11 / PVDF | Hermeticidad — barrera de presión |\n| 3 | **Armadura de presión** | Alambre de acero ~85° | Resiste presión interna |\n| 4-5 | **Armaduras de tracción** | Alambre de acero ~35-55° | Carga axial y peso propio |\n| 6 | **External sheath** | Polímero | Protección mecánica y marina |\n\n---\n\n## 🌡️ Selección de barrera por temperatura\n\n| Polímero | T máxima |\n|---|---|\n| HDPE | 60 °C |\n| PA12 | 80 °C |\n| PA11 | 90 °C |\n| **PVDF** | **130 °C** |\n\n---\n\n## 🏆 Certificación obligatoria\n\n> Requiere **TPICP** (Third Party Independent Certification) por: **DNV**, **Bureau Veritas**, **Lloyd\'s Register** o **ABS**.' },
          { order: 2, title: 'Análisis de fatiga en risers flexibles API 17J',
            content: '## 📉 Fatiga en risers API 17J — Análisis obligatorio\n\nLos risers API 17J soportan cargas **dinámicas continuas** durante toda su vida útil.\n\n---\n\n## ⚠️ Fuentes de daño por fatiga\n\n| Fuente | Zona afectada | Descripción |\n|---|---|---|\n| **VIV** | Cuerpo del riser | Corrientes marinas → desprendimiento de vórtices |\n| **WIO** | Top connector + TDZ | Movimientos de 6 GDL del FPSO / plataforma |\n| **TDZ** | Punto de contacto fondo | Máxima concentración de ciclos de flexión |\n\n---\n\n## 📐 Criterios de diseño\n\n| Criterio | Valor requerido |\n|---|---|\n| Daño acumulado (Palmgren-Miner) | **D < 0.1** → factor de seguridad **×10** |\n| Condición extrema para TDZ | Ola **100 años** + corriente **10 años** |\n| MBR dinámico | Nunca superar bajo ninguna condición de carga |\n\n---\n\n## 📊 Curvas S-N\n\n> La curva S-N de fatiga de **cada componente** debe obtenerse de ensayo propio del fabricante.\n> No es válido usar curvas S-N genéricas de acero para el flexible.' },
          { order: 3, title: 'Gestión del anular y monitoreo de integridad offshore',
            content: '## 🔵 Gestión del anular — Annulus Management\n\nEl anular (entre barrera y armaduras) requiere **gestión activa** durante toda la operación.\n\n---\n\n## 🔬 ¿Qué se acumula en el anular?\n\n- 💨 **H₂S, CO₂, CH₄** — permean a través de la barrera polimérica\n- 💧 **Agua** — condensación por gradiente térmico\n- ⚠️ En concentración suficiente → atacan las **armaduras de acero**\n\n---\n\n## 📋 Protocolo de venteo\n\n| Parámetro | Valor |\n|---|---|\n| Frecuencia | Cada **3-6 meses** |\n| Análisis del gas | H₂S, CO₂, CH₄ |\n| Umbral de alerta | Volumen > **150%** del modelo del fabricante |\n| Acción ante alerta | Evaluación de integridad intensificada |\n\n---\n\n## 📡 Monitoreo continuo\n\n| Tecnología | ¿Qué detecta? |\n|---|---|\n| **DTS** (Distributed Temperature Sensing) | Fugas por anomalía térmica en tiempo real |\n| **Sensores de presión en anular** | Sobrepresión temprana |\n| **Inspección ROV** | End fittings y cuerpo del riser |\n\n> 🤿 Inspección ROV: frecuencia mínima **anual** para risers API 17J en servicio.' },
        ],
        quiz: {
          title: 'Evaluación Premium M9 — API 17J Flexibles Submarinos',
          questions: [
            { questionText: '¿Con qué norma ISO es técnicamente idéntica API Spec 17J?', options: ['ISO 13628-1', 'ISO 13628-2', 'ISO 13628-4', 'ISO 15156'], correctAnswer: 1, explanation: 'API Spec 17J es técnicamente idéntica a ISO 13628-2, ambas cubren tuberías flexibles no pegadas para aplicaciones submarinas.' },
            { questionText: '¿Cuál es la función de la carcass de acero inoxidable en un flexible API 17J?', options: ['Resistir la presión interna del fluido', 'Anti-colapso ante presión hidrostática externa y succión interna', 'Conectar las armaduras de tracción', 'Proteger contra UV en superficie'], correctAnswer: 1, explanation: 'La carcass es la capa más interior y actúa como elemento anti-colapso contra la presión hidrostática externa del agua y la succión interna.' },
            { questionText: '¿Cuál es la profundidad máxima de agua que cubre API 17J?', options: ['500 m', '1500 m', '2000 m', '3000 m (10,000 ft)'], correctAnswer: 3, explanation: 'API Specification 17J cubre instalaciones de flexibles hasta 3000 m (10,000 ft) de profundidad de agua.' },
            { questionText: '¿Qué factor de seguridad mínimo de fatiga requiere API 17J (regla Palmgren-Miner)?', options: ['Factor 2 (D < 0.5)', 'Factor 5 (D < 0.2)', 'Factor 10 (D < 0.1)', 'Factor 20 (D < 0.05)'], correctAnswer: 2, explanation: 'API 17J requiere factor de seguridad de fatiga de 10, equivalente a daño acumulado D < 0.1 en la vida útil del proyecto.' },
            { questionText: '¿Qué organismo puede emitir la certificación TPICP requerida por API 17J?', options: ['Solo API', 'DNV, Bureau Veritas, Lloyd\'s Register o ABS', 'Solo el fabricante del flexible', 'Solo la empresa operadora'], correctAnswer: 1, explanation: 'API 17J requiere certificación TPICP por organismos reconocidos: DNV, Bureau Veritas, Lloyd\'s Register o ABS.' },
            { questionText: '¿Cuál es el rango de temperatura de operación de la barrera de PVDF según API 17J?', options: ['Hasta 60 °C', 'Hasta 80 °C', 'Hasta 90 °C', 'Hasta 130 °C'], correctAnswer: 3, explanation: 'La barrera de PVDF (Polyvinylidene Fluoride) permite operación hasta 130 °C, siendo el polímero de mayor temperatura en API 17J.' },
            { questionText: '¿Qué zona del riser concentra los ciclos de flexión por contacto con el lecho marino?', options: ['Top connector (conector superior)', 'Touchdown Zone (TDZ)', 'Mid-water arch', 'Hang-off point'], correctAnswer: 1, explanation: 'La Touchdown Zone (TDZ) es donde el riser contacta el lecho marino y concentra los ciclos de flexión críticos para fatiga.' },
            { questionText: '¿Qué condición extrema de diseño aplica al análisis de fatiga de la TDZ?', options: ['10-year wave + 10-year current', '100-year wave + 10-year current asociada', '1000-year wave + 100-year current', '50-year wave sin corriente'], correctAnswer: 1, explanation: 'El análisis extremo de TDZ usa la combinación de ola de 100 años con corriente asociada de 10 años.' },
            { questionText: '¿Cuál es el indicador de alerta en el monitoreo del anular de un flexible API 17J?', options: ['Venteo anual > 10 litros', 'Volumen venteado > 150% del modelo de permeación del fabricante', 'Detección de CO₂ en el gas venteado', 'Temperatura del anular > 60 °C'], correctAnswer: 1, explanation: 'Exceder el 150% del volumen de permeación esperado según el modelo del fabricante es el indicador estándar de alerta.' },
            { questionText: '¿Para qué sirve el DTS (Distributed Temperature Sensing) en risers API 17J?', options: ['Medir temperatura del agua de mar en profundidad', 'Detectar fugas por anomalía térmica y monitorear temperatura del barrier en tiempo real', 'Controlar temperatura de inyección de inhibidores', 'Medir la elongación del riser'], correctAnswer: 1, explanation: 'El DTS mide distribución de temperatura a lo largo del riser; una anomalía térmica localizada puede indicar una fuga o permeación anómala.' },
          ],
        },
      },
    ];

    for (const modData of modules) {
      const { lessons, quiz, ...moduleFields } = modData;
      const savedModule = await this.modulesRepo.save(
        this.modulesRepo.create({
          order: moduleFields.order,
          title: moduleFields.title,
          description: moduleFields.description,
          isPremium: moduleFields.isPremium,
          passingScore: moduleFields.passingScore,
        }),
      );
      this.logger.log(`  ✅ Módulo ${savedModule.order}: ${savedModule.title}`);

      for (const lessonData of lessons) {
        await this.lessonsRepo.save(
          this.lessonsRepo.create({ ...lessonData, moduleId: savedModule.id }),
        );
      }

      const savedQuiz = await this.quizzesRepo.save(
        this.quizzesRepo.create({ title: quiz.title, moduleId: savedModule.id }),
      );
      for (const q of quiz.questions) {
        await this.questionsRepo.save(
          this.questionsRepo.create({ ...q, quizId: savedQuiz.id }),
        );
      }
      this.logger.log(`    📝 Quiz: "${quiz.title}" (${quiz.questions.length} preguntas)`);
    }

    this.logger.log('✅ Seed técnico completado — 9 módulos únicos API 15S/15SA/15SIH/17J');
    return { message: 'Seed ejecutado', modules: modules.length };
  }
}
